services:
  moodle_db:
    image: postgres:11
    volumes:
      - "moodledb_apache:/var/lib/postgresql/data"
    environment:
      POSTGRES_DB: $MOODLE_DB_NAME
      POSTGRES_USER: $MOODLE_DB_USER
      POSTGRES_PASSWORD: $MOODLE_DB_PASSWORD

  moodle:
    image: ellakcy/moodle:postgresql_apache_latest
    volumes:
      - "www_apache:/var/www/html"
    ports:
      - "8082:80"
    environment:
      MOODLE_URL: $MOODLE_URL
      MOODLE_ADMIN: $MOODLE_ADMIN
      MOODLE_ADMIN_PASSWORD: $MOODLE_ADMIN_PASSWORD
      MOODLE_ADMIN_EMAIL: $MOODLE_ADMIN_EMAIL
      MOODLE_DB_HOST: "moodle_db"
      MOODLE_DB_TYPE: "pgsql"
      MOODLE_DB_USER: $MOODLE_DB_USER
      MOODLE_DB_PASSWORD: $MOODLE_DB_PASSWORD
      MOODLE_DB_NAME: $MOODLE_DB_NAME
      MOODLE_REVERSE_LB: $MOODLE_REVERSE_LB
      MOODLE_SSL: $MOODLE_SSL
      MOODLE_EMAIL_TYPE_QMAIL: $MOODLE_EMAIL_TYPE_QMAIL
      MOODLE_EMAIL_HOST: $MOODLE_EMAIL_HOST
    depends_on:
      - moodle_db
volumes:
  moodledb_apache:
  www_apache:
